### ISSUE TITLE
refactor yamls to remove `_all` param/field

### ISSUE THREAD

**Issue by lauramaxwell** [Gilead-BioStats/gsm.kri#5]
I'm leaning towards moving to this format for the specs in a future release. I think this would largely remove the need for the `_all` keyword. 

```
spec: 
    - domain: mapping
.     table: labs
    - domain: mapping
      table: ae
      columns: 
       - name: SubjectID:
         type: character
         source_col: subjid
       - name: serious
         required: true
         type: character
         source_col: aeser    
```

_Originally posted by @jwildfire in https://github.com/Gilead-BioStats/gsm/issues/1952#issuecomment-2517685291_
